version: '3.8'


services:
  database:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - ./backend:/db
  backend:
    build:
      context: .
      dockerfile: _dockerfiles/app/backend/dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000
    volumes:
      - ./backend/app:/code/app
  frontend:
    build:
      context: .
      dockerfile: _dockerfiles/app/frontend/dockerfile
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - ./frontend/app:/code
