FROM python:3.9

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /code

COPY ./backend/requirements.txt  /code/requirements.txt

RUN apt-get update && \
    apt-get install -y && \
    pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./backend/app /code/app

CMD ["uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]